#!/bin/bash
set -e

# Variables (passed from env or set here)
# DOCKERHUB_REPO, DOCKERHUB_USERNAME, DOCKERHUB_TOKEN, AWS_REGION, DEPLOY_ENV should be available as env vars

DEPLOY_ENV=${DEPLOY_ENV:-prod}
DOCKER_TAG=${DOCKER_TAG:-latest}

# Log in to Docker Hub
echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

# Pull the image
docker pull "$DOCKERHUB_REPO":"$DOCKER_TAG"

# Stop and remove existing container if it exists
docker stop webhello-"$DEPLOY_ENV" || true
docker rm webhello-"$DEPLOY_ENV" || true

# Fetch parameters from AWS Parameter Store and save to .env file
# We assume parameters are stored under /webhello/$DEPLOY_ENV/
# Ensure AWS CLI is installed on the server
ENV_FILE=".env.webhello-$DEPLOY_ENV"
echo "# Generated by deployment script on $(date)" > "$ENV_FILE"

# Fetch parameters, remove prefix, and format as KEY=VALUE
aws ssm get-parameters-by-path --path "/webhello/$DEPLOY_ENV/" --with-decryption --region "$AWS_REGION" --query "Parameters[*].[Name,Value]" --output text | \
  sed "s|^/webhello/$DEPLOY_ENV/||" | \
  awk '{print $1 "=" $2}' >> "$ENV_FILE"

# Run the new container
# Use port 80 as standard since environments are on different servers
PORT=80

docker run -d \
  --name webhello-"$DEPLOY_ENV" \
  -p "$PORT":80 \
  --env-file "$ENV_FILE" \
  "$DOCKERHUB_REPO":"$DOCKER_TAG"
